name: "test_test"
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install --no-cache-dir -r ./requirements.txt
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
  
    - name: Install dependencies
      run: pip install --no-cache-dir -r ./requirements.txt
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 193.106.99.68
        user: ${{secrets.SSH_USER}}
#        public_key: ${{secrets.SSH_PUBLIC_KEY}}
#        private_key: ${{secrets.SSH_PRIVATE_KEY}}
        password: ${{secrets.SSH_PASSWORD}}
        port: ${{ secrets.SERVER_PORT }}
        command: |
          cd /home/clevtech/Documents/contest/test_test;
          git pull;
          docker-compose up down;
          docker-compose up -d --build;